### ISSUE TITLE
Running command with `switch-format` argument and `--dry-run` option fails after updating to `symplify/config-transformer:11.2.1.72`

### ISSUE THREAD

**Issue by localheinz** [symplify/config-transformer#11]
After updating `symplify/config-transformer`, our builds have been failing on GitHub Actions because of two breaking changes:

- running the command with 

  ```sh
   vendor/bin/config-transformer switch-format config/ --dry-run
  ```

  fails with exit code `1` and output

  ```
  In Finder.php line 633:

    The "switch-format" directory does not exist.


  switch-format [-n|--dry-run] [--] [<sources>...]
  ```

  because the `switch-format` argument (to select the command, which has probably now become the default command) has been removed

- running the command with

  ```sh
   vendor/bin/config-transformer config/ --dry-run
  ```

   fails with exit code `1` and output 

  ```

   [ERROR] 0 file(s) should be switched to PHP

  ```

  when no files where found that needed to be transformed.

  It would be great if the old behaviour, exiting with exit code `0` when no files where found that needed to be transformed, could be restored.

For reference, see https://github.com/symplify/config-transformer/compare/11.1.27.72...11.2.1.72.

**Comment by TomasVotruba** [comment]
Hi @localheinz ,

thanks for reporting. I'm just checking this package for my other project.

Yes, the command became the default. I thought Symfony can handle it with or without name.

How do you use this? It should only fail in CI when there are some files to change.

**Comment by localheinz** [comment]
@TomasVotruba 

Thank you for the quick reply!

We are running

```yaml
      - name: "Run symplify/config-transformer"
        run: "vendor/bin/config-transformer --ansi --dry-run config/"
```

as a step in a GitHub Actions workflow, to ensure that developers do not check in configuration files for a Symfony application in `yaml` format.

**Comment by TomasVotruba** [comment]
This could help: https://github.com/symplify/config-transformer/pull/12

Btw, any idea how to make Symfony application use default command, but also allow the explicit name?

**Comment by localheinz** [comment]
@TomasVotruba 

Taking a 👀!

**Comment by localheinz** [comment]
@TomasVotruba 

Perhaps this helps: https://github.com/symplify/config-transformer/pull/13
