### ISSUE TITLE
symfony/dependency-injection locked to 6.1.* - Necessary?

### ISSUE THREAD

**Issue by gndk** [symplify/config-transformer#19]
`symfony/dependency-injection` is locked to `6.1.*` since https://github.com/symplify/config-transformer/commit/64f6f94bde4441045ef9ec8f20d9cbf4cbd3a73f.

Is this still necessary? Unfortunately it prevents me from updating for some time now. Current Symfony version is `6.3`.

**Comment by TomasVotruba** [comment]
The tagged version is scoped and downgraded, so this is no limit, see:
https://packagist.org/packages/symplify/config-transformer

**Comment by gndk** [comment]
Ah, turns out my Renovate Bot is to blame then. It couldn't deal with the jump from `11.1.24` to `12.0.5` because of the incompatible releases in between. Manually upgrading worked fine.

Thanks!

**Comment by TomasVotruba** [comment]
Perfect :+1:
