### ISSUE TITLE
Error ($key) must be of type string

### ISSUE THREAD

**Issue by Evgeny1973** [symplify/config-transformer#21]
Hello!
Symfony 6.2. When i try to convert services.yaml i got an error:
```
 [ERROR] Symplify\PhpConfigPrinter\NodeFactory\Service\ServiceOptionNodeFactory::shouldSkip(): Argument #1     
         ($key) must be of type string, int given, called in /var/www/html/vendor/symplify/config-transformer/vendor/symplify/php-config-printer/src/NodeFactory/Service/ServiceOptionNodeFactory.php on line 37 
```
I have another specialized services.yaml file, in a different place, the converter also crashes on it with the same error.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated example of YAML file causing this issue, that way we can reproduce the bug.
