### ISSUE TITLE
[Feature] Configuration to exclude some files or folder

### ISSUE THREAD

**Issue by AlexandreGerault** [symplify/config-transformer#23]
Hi 👋 

There's no issue template or what so ever like that so I apologize if you don't like this 🙏 

I think it could be great to add a configuration (like phpstan, phpunit etc) to exclude some files or directories, as sometimes you have to keep with yaml configuration (unfortunately) when bundles have some unsupported php configuration files.

I still didn't read the source code but if the idea is ok for you, I might look into it 👍

**Comment by TomasVotruba** [comment]
Hey, sounds good.
How would the command look like with such feature?

**Comment by AlexandreGerault** [comment]
Hmm I don't know. If a command is needed maybe something like
```
vendor/bin/config-transformer --exclude="config/grid.yaml,config/resource"
```
And something similar too if a config file is supported
```
// config-transformer.yaml or config-transformer.neon
exclude:
    - config/grid
    - config/resources
```
However I don't realize how much work that would require for each option.

**Comment by TomasVotruba** [comment]
I'm going through issues to prune the old or accepted ones :) go for the PR :+1: 

Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.
Feel free to send PR with it :+1:
