### ISSUE TITLE
[DX] Allow processing single file too

### ISSUE THREAD

**Issue by TomasVotruba** [symplify/config-transformer#30]
Now it's only possible to process whole dirs:

```bash
vendor/bin/config-transformer convert /config /app/config
```

---

The single file should be easy to process too:

```bash
vendor/bin/config-transformer convert file.yaml
```

**Comment by samsonasik** [comment]
I forgot what the functionality of this lib 😁

I will try

**Comment by samsonasik** [comment]
I created PR :

- https://github.com/symplify/config-transformer/pull/31

for it.

**Comment by samsonasik** [comment]
Handled at https://github.com/symplify/config-transformer/pull/31
