### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by k0d3r1s** [symplify/config-transformer#36]
can you make this compatible with symfony 7?

**Comment by TomasVotruba** [comment]
Should be compatible with Symfony 5.3+

What exactly is the error you're getting?

**Comment by k0d3r1s** [comment]
my issue seems to rely on my config :(  
`composer require symplify/config-transformer:12.3.4 --dev` seems to install while `composer require symplify/config-transformer --dev` does not. i have "minimum-stability" set to "dev" in my composer

**Comment by TomasVotruba** [comment]
That looks some bug in composer, possibly locked with other transitional deps. Glad you made it work :+1: 

I use PHP 8.2 and it works well without any extra work:

```bash
➜  www mkdir test-install
➜  www composer require symplify/config-transformer
./composer.json has been created
Running composer update symplify/config-transformer
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking symplify/config-transformer (12.3.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading symplify/config-transformer (12.3.4)
  - Installing symplify/config-transformer (12.3.4): Extracting archive
```
