### ISSUE TITLE
after using this took, symfony is not finding my new php config files by default

### ISSUE THREAD

**Issue by arderyp** [symplify/config-transformer#37]
Symdony 5.4

### config structure
config/
--services.php
--packages/
----a.php
----b.php
----...
--routes/
----...

### behavior
`service.php` is imported [here](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L61).  But the [code block above](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L54-L55) that handles importing `config/packages/*` only handles yaml files. Likewise [with routing](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L78-L85), despite the [docblock](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L68) indicating `{yaml,php}`.

I can import the files manually, by adding the following to my `config/services.php`, for example:

```
# config/services.php
$containerConfigurator->import('packages/*.php');

# config/routes.php
$routingConfigurator->import('routes/*.php');
```

Am I doing this right, or missing something? Does symfony not support these types of php config files out of the box?

I know you talk about adding loader logic in your blog post [here](https://tomasvotruba.com/blog/2020/07/27/how-to-switch-from-yaml-xml-configs-to-php-today-with-migrify/), but I don't have any such extension and am not entirely sure where you are using this extension.

Thanks for yet another cool tool @TomasVotruba !

**Comment by arderyp** [comment]
Adding those lines to `services.php` and `routes.php` seem to solve the issue of imports when running the app.

however, now my phpunit fails before running any tests with:

```
Symfony\Component\Config\Exception\LoaderLoadException: There is no extension able to load the configuration for "services" (in "/home/arderyp/repo/config/services.php"). Looked for namespace "services", found "api", "dama_doctrine_test", "doctrine", "doctrine_migrations", "sensio_framework_extra", "framework", "monolog", "security", "twig", "web_profiler", "webpack_encore" in /home/arderyp/repo/config/services.php (which is being imported from "/home/arderyp/repo/src/Kernel.php").
```

I'm still trying to figure this one out

**Comment by arderyp** [comment]
nevermind, I see the a answer to my main question here: https://symfony.com/doc/5.x/configuration.html#configuration-formats

**Comment by TomasVotruba** [comment]
I'm glad you've found the solution :+1: 

Yes, the Kernel needs to be updated as Symfony unfortunatelly hardcodes the config loading format.

It's in the section 3 of the post:
https://tomasvotruba.com/blog/2020/07/27/how-to-switch-from-yaml-xml-configs-to-php-today-with-migrify/

**Comment by arderyp** [comment]
@TomasVotruba have you struggled with yaml config options that are straight up missing or unavaialle in PHP? I've run into at least three so far, all on the FirewallConfig, and I presume there are many more. Example: https://github.com/symfony/symfony/issues/53987

**Comment by TomasVotruba** [comment]
Not yet, as afaik the configs are generated from your current Symfony version.

**Comment by arderyp** [comment]
my issue is confirmed and the fix is working for me :) https://github.com/symfony/symfony/pull/53989
